### ISSUE TITLE
allow Log::Report::Dispatcher::File format code to be specified in config file

### ISSUE THREAD

**Issue by clemep-sios** [markov2/perl5-Log-Report#8]
I'm using Log::Report::Dispatcher::File for a Dancer2 app and I'm trying to specify a subroutine "format" handler, like so (in Dancer2 YAML config):

```
engines:
  logger:
    LogReport:
      dispatchers:
        default:              
          type: FILE          
          format: "sub { 'HERE ' . $_[0] }"
```

It doesn't seem to work (it just gives an error "unknown parameter"). Is there a way to make that work? Configuring through the app's perl code seems like a difficult and undesirable requirement.

The following quick code change seems to make the above work:

```
--- File.pm.orig   2021-02-14 12:17:38.188639047 -0500
+++ File.pm        2021-02-14 12:15:47.404201991 -0500
@@ -42,6 +42,7 @@ sub init($)
     my $format = $args->{format} || sub { '['.localtime()."] $_[0]" };
     $self->{LRDF_format}
       = ref $format eq 'CODE' ? $format
+      : $format =~ /^sub/ ? eval($format)
       : $format eq 'LONG'
       ? sub { my $msg    = shift;
               my $domain = shift || '-';
```

Does that seem like a useful change? Or is there a better way to do this?

Thanks.
